### ISSUE TITLE
Update lag / bug

### ISSUE THREAD

**Issue by bgordonnhs** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#110]
Hello, 

I've noticed that in the most recent version there seems to be a little bug / lag in the SPC updating to meet the formatting changes being input.

e.g. when I'm changing the options for dot size, fonts, colours etc. (anything really!) the SPC doesn't update to match the changes until I've toggled the following option off and on again:
![image](https://user-images.githubusercontent.com/122809109/215744622-1cccf5c8-577e-4ace-82d5-049857f8c039.png)

It does seem to be this option in particular I'm having to toggle off and on again to see the changes.

This is also the case when I've added slicers to the page, for the SPC to update with filtered data I need to toggle that option off and on again to see the change.

Thanks,
Bethany

**Comment by andrjohns** [comment]
Sorry about that! All fixed up by #112
