### ISSUE TITLE
Adding summary icons to charts

### ISSUE THREAD

**Issue by nickkrollnhs** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#116]
Please can the MDC summary icons be added to the SPC charts. Icons can be downloaded,

- as PNG files here:  https://github.com/nhsengland/making-data-count/tree/main/Icons
- SVG versions used in R package https://github.com/nhs-r-community/NHSRplotthedots/tree/main/inst/icons from this update https://github.com/nhs-r-community/NHSRplotthedots/pull/163

**Variation icon:**

The first icon represents the observed variation in the latest data point - regardless of what rule has been broken.

**Common cause variation**
1) IF latest data point is common cause variation THEN VariationIconCommonCause.png
**Special cause improvement**
1) IF latest data point is special cause improvement high point THEN VariationIconImprovementHigh.png
2) IF latest data point is special cause improvement low point THEN VariationIconImprovementlow.png
**Special cause concern**
1) IF latest data point is special cause concern high point THEN VariationIconconcernHigh.png
2) IF latest data point is special cause concern low point THEN VariationIconImprovementlow.png

**Assurance icon**

The second icon represents the assurance of the process, and how likely this process will hit the target in the future. The 3 sigma control limits should be used for the LPL and UPL calculations.

1) IF improvement direction = High THEN:
IF target >=UPL line THEN AssuranceIconFail.png
IF target < UPL AND > LPL THEN AssuranceIconHitOrMiss.png
IF target <= LPL THEN AssuranceIconpass.png

2) IF improvement direction = low THEN:
IF target<= LPL line THEN AssuranceIconFail.png
IF target < UPL AND > LPL THEN AssuranceIconHitOrMiss.png
IF target  >=  UPL THEN AssuranceIconpass.png

Please can the icons be made visible in the top right hand corner of the SPC chart.

Many thanks,
Nick Kroll

**Comment by andrjohns** [comment]
Closed by #156 and #146
