### ISSUE TITLE
Additional visual for summary icon tables

### ISSUE THREAD

**Issue by nickkrollnhs** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#117]
One of the most effective and popular tools that organisations use is a summary icon table.

This summarises a range of metrics, their latest performance and the variation and assurance icon for that metric. The photo below is a PowerBI matrix visual, we sometimes use the standard table visual if only 1 group (Trust in this case) needs to be represented. The fields can be added or removed, for example I may not want to show the UPL and LPL in my final report. Tooltips are added to show the SPC chart if the user hovers over a particular metric.

If possible, we would like to ask if this visual can be added to the development pipeline.

![image](https://user-images.githubusercontent.com/110397804/221562547-75ec6a7f-0314-4398-8ca7-cb6a6862995b.png)

Many thanks,
Nick

**Comment by andrjohns** [comment]
Hmmm this is a bit more complex since it's an entirely new visual and it's derived from the SPC charts of multiple indicators and/or groups, rather than just a single SPC chart. 

Unfortunately I think this is a little out of scope for the current visual

**Comment by andrjohns** [comment]
Are there any possible adaptations that could be made for the current visual that would help you in constructing this visual yourself?

**Comment by SeanOS66** [comment]
This is also what I would like to do, however, on the Feature request I have just posted, which if you implemented, would assist  @nickkrollnhs with his request. (just replicate my suggestion for every KPI on the summary page)

**Comment by andrjohns** [comment]
A summary table with icons is now implemented ([see guide here](https://aus-doh-safety-and-quality.github.io/PowerBI-SPC/SummaryTable.html) for more details)
