### ISSUE TITLE
Ability to print chart to pdf from powerbi

### ISSUE THREAD

**Issue by matthewmcilorum** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#125]
Hi,

Users of my dashboard containing this chart are having issue when printing to PDF. This chart does not appear to be supported in this function and is useful for adding as appendix/minutes to meetings. Not sure if this is an issue with the chart itself or with Power BI not allowing custom visuals to be printed?

It works in desktop but not when its published through the PBI service

Hoping you might have an idea around this

thanks
[ED SPC.pdf](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/files/11334333/ED.SPC.pdf)

**Comment by andrjohns** [comment]
Unfortunately PowerBI only allows exporting to PDF once a visual has been published to the Microsoft store and additionally certified.

We'll be submitting the visuals to the store next week, but the acceptance and additional certification process can take a few months

**Comment by andrjohns** [comment]
@matthewmcilorum I'm very happy to say that the visual is now Certified in the Microsoft store! You should now be able to install the visual from AppSource and print/export to PDF with no issues
