### ISSUE TITLE
Version of chart with highest limit 2 sigma

### ISSUE THREAD

**Issue by matthewmcilorum** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#126]
I have been asked by my board if its possible to have a version of this chart in which the control limits are 2 and 1 sigma instead of the current 3 and 2 so the astro points highlight when it go past the 2 sigma. While the current version is great for some data having this other option would be useful for other scenarios.

**Comment by andrjohns** [comment]
@matthewmcilorum Apologies for taking so long to get to this! The visual now has options for enabling/disabling the display of the 1/2/3 sigma limits, and the astronomical points and two-in-three menus now also have an option for the sigma limit to use when flagging.

These features will also be in the next submission to MS (submitting within the next week).
