### ISSUE TITLE
Y axis % values not showing correctly

### ISSUE THREAD

**Issue by BlueBe11** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#191]
I have used PowerBI-SPC visual for a little while now and when I was using it for rates, it was showing it perfectly when selected in 'Data Settings' for 'Report as percentage' as 'Yes'.
<img width="253" alt="image" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/150334152/10aa8c4e-7c74-4f9c-9159-dc3d8be6396b">

Now it shows weird, where it should be 8.0% it shows 0.08%.
<img width="160" alt="image" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/150334152/2c6d034c-ea13-463b-afb4-6bb9512f36ca">

This happened across the board in all my PBI reports for PowerBI-SPC visuals, I think after the updated version kicked in. Could anyone advise if it is something I am doing wrong? Thank you.

**Comment by andrjohns** [comment]
Sorry to hear that! Can I just get a little more information:

- What version of the visual are you using (you can check by right-clicking on the visual and selecting 'About')?
- What chart type are you using?
- Have you set a multiplier?

**Comment by BlueBe11** [comment]
Hi,
<img width="272" alt="image" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/150334152/96efbae7-0556-4f42-baf2-38e862562343">
<img width="86" alt="image" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/150334152/bdfe1d3b-c4b1-4d89-a82e-786e8c86ee3d">

**Comment by andrjohns** [comment]
Ah I think I know what I've done with the percentage-labelling logic. For now you'll need to specify a multiplier of 100 if you want the percentages to be correctly reported (i.e., 8.0% instead of 0.08%), but I'll get this fixed for the next version

**Comment by BlueBe11** [comment]
Oh, fab, thank you so much for your prompt response and solution :)
