### ISSUE TITLE
Internal Error: t.at is not a function

### ISSUE THREAD

**Issue by alex-cplee** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#193]
Hi Andrew and HQIU,

I am trying to get both SPC and funnel plot visuals working in our organisation but they both have the same an error output "t.at is not a function".

<img width="297" alt="PowerBI SPC error" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/93962658/87a67cad-af20-4253-be0b-153e7d5bed63">

Our Power BI version is 2.107.841.0 64-bit (July 2022) - I know it is old but it is what we are using. I am suspecting the older version of Power BI Desktop may yet to support the .at method, although there might be other reasons (e.g. organisation security settings?) that might cause this issue.

Alex

**Comment by shauneccles** [comment]
Which version of the Visual are you using?

Given how old the PBI version is have you tried using the oldapi releases `PBISPC.1.4.0.3-oldapi.pbiviz`?

**Comment by alex-cplee** [comment]
_Which version of the Visual are you using?_

I am using the latest version in the appsource - 1.4.0.2 (https://appsource.microsoft.com/en-us/product/power-bi-visuals/healthdepartmentwa1667894240640.powerbi-spc-charts?tab=DetailsAndSupport) 

_have you tried using the oldapi releases PBISPC.1.4.0.3-oldapi.pbiviz?_
this is difficult because my organisation does not allow Github access. I tried to download one of the pbiviz file and send it to my work inbox but the file got blocked; and we cannot use own USB to transfer file over (and you can take a guess where I am working at :) ). 

Anyway if I publish a dashboard with a SPC/funnel plot in Power BI service, the visual is working as expected. The error message only appears in our version of Power BI Desktop; luckily I can still drag and drop fields, it's just that I cannot see the output until I publish the dashboard which is convenient.

**Comment by andrjohns** [comment]
@alex-cplee Sorry about that! It looks like the `.at()` member function is somewhat new and is only recognised with pretty recent javascript runtimes. I've merged #205 with a fix, can you see if the development version works for you locally now?

**Comment by alex-cplee** [comment]
@andrjohns Thanks for the fix. Our organisation blocks Github access and does not allow attachment of any file with typescript-like file in email, and we are not allowed to transfer file via USB either. Unfortunately for me the only way I can check if the fix works is for you to push the development version to production. As far as I can see the fix works for my home version Power BI Desktop (2.122.746.0 64-bit (October 2023 release)), so it should be safe to push the fix to PROD without affecting other users. Once you update the PROD version I will let you know if the fix works!

**Comment by andrjohns** [comment]
Great! Aiming to submit a new version next week, so should be updated in the new year
