### ISSUE TITLE
Unable to Change Date Formatting

### ISSUE THREAD

**Issue by shauneccles** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#194]
Thank you for providing such an excellent resource.

I'm having some issues with the visual around date format display in the date axis and tooltips.

Changing any of the Date Format settings within the Visuals settings does not appear to do anything to the Visual - the date label and tooltip values are static.

Expected behaviour would be that changes applied in the Date Format settings are reflected immediately on the visual when the settings are changed.
 
PBI Version: Version: 2.122.1066.0 64-bit (October 2023)
Visual Version: PBISPC.1.4.0.3.pbiviz

**Comment by shauneccles** [comment]
Not a bug, but likely something that requires either documenting or updating the visual to cater for date hierarchy structures.

In order for the Date Format settings to be effective, the raw date value needs to be used, not the date hierarchy.

Using the date hierarchy works, but does not respect the Date Format settings.

**Comment by andrjohns** [comment]
Closed by #219
