### ISSUE TITLE
Feature Request: Date label for all datapoints

### ISSUE THREAD

**Issue by shauneccles** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#195]
I would like the ability to have a date label on the x-axis for every datapoint on the SPC chart.

Currently when using the Visual the date labels, I have :
![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/21007065/dd63152b-9a6b-4617-80e2-4f1752328657)

Desired date labelling state:
![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/21007065/d6cbeee2-efab-4f64-b785-916a91f3c92e)

This style of labelling is what my organisation is used to and expecting - having the labels at a 45 degree angle is also acceptable.

PBI Version: Version: 2.122.1066.0 64-bit (October 2023)
Visual Version: PBISPC.1.4.0.3.pbiviz

**Comment by andrjohns** [comment]
Thankfully this is already possible with the visual settings, under the X-Axis tick settings you can change the number of ticks shown and the rotation of the tick labels:


| Setting | Plot |
|--|--|
| ![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/93a18c28-6edd-4833-8fee-15ee3652163e) | ![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/ed9da214-86e4-40e6-9714-17a44336ab8d) |

Does that work for you?

**Comment by shauneccles** [comment]
Ah, I missed that, thank you :)
