### ISSUE TITLE
Outlier points all black

### ISSUE THREAD

**Issue by paddy-devan** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#202]
Hi, I'd firstly like to say that I'm incredibly happy to have found this visual and it's perfect for my NHS trust's requirements - thank you for developing! I've configured the outlier highlighting rules to conform to NHS standards and have ran into the bug that all highlighted points show as black rather than the specified colour. This is both in PBI desktop and when published on the service:
![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/109914304/ff8a47df-1695-47dc-991d-4a0695c18869)

*Addition* - For further context this seems to be an issue only when using conditional formatting to configure the 'Improvement direction' parameter. I am also using the January 2023 release of Power BI desktop (and can't upgrade at the moment because of my trust's IT policies).

Thanks!

**Comment by andrjohns** [comment]
Great to hear that you've found it useful and apologies for the issue! For the improvement direction conditional formatting, you need to pass the values in lower-case (i.e., `"increase"`, `"neutral"`, or `"decrease"`). Does it work if you make that change?

Improving the documentation and handling for the conditional formatting is on my to-do list for this week, so the next version should be a bit more robust and informative for this!

**Comment by paddy-devan** [comment]
That does work thank you and I figured that out after doing a bit more experimenting!
