### ISSUE TITLE
Report as percentage should multiply by 100

### ISSUE THREAD

**Issue by paddy-devan** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#203]
Hi again, just a thought that when the 'Report as percentage' option is selected should the values not be multiplied by 100? This would align with the rest of Power BI as most values that are displayed as a percentage are actually outputted from the measure as a decimal.

Many thanks!

**Comment by andrjohns** [comment]
I'm going to reopen this since it's a bug on my to-do list to fix

**Comment by andrjohns** [comment]
Thanks for the report! Fixed
