### ISSUE TITLE
Axis line passing through points

### ISSUE THREAD

**Issue by alexmcqueen** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#210]
Currently it appears that the axis line will pass in front of a scatter data point. It would be preferable if the line could pass behind the scatter point. This is prominent when the axis line colour and scatter point are a different colour.  

I have attached a photo of the behaviour and the preferable behaviour. Please close and apologises if I have missed the setting for this!

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/59609839/d4d680d6-60a7-4f1b-80db-7331f98a9904)

**Comment by andrjohns** [comment]
Thanks for the report! Should be fixed now
