### ISSUE TITLE
y-axis tick text cut off 

### ISSUE THREAD

**Issue by paddy-devan** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#211]
Hi, I've noticed that the y-axis tick text tends to get cut off, especially for longer numbers or where the text size has been increased a bit :)

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/109914304/ee515e64-100a-4e05-97a4-281b168f8d21)

**Comment by andrjohns** [comment]
Good catch! Fixed
