### ISSUE TITLE
NHS Assurance and Variation Icons not working

### ISSUE THREAD

**Issue by charlotte681** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#248]
Hello,

I am using your visual for NHS data and wondered if there were issues with the NHS icons not working?
I only ever get the common cause variation symbol, where as I would like to see the high/low cause icons.

Is there some on going work on the icons, or am I possibly missing something?

Thanks
Charlotte

**Comment by andrjohns** [comment]
Have you also enabled any of the outlier patterns to be highlighted? The icons are determined by the patterns you've enabled

If that's not the issue, can you show a screenshot of the behaviour?

**Comment by JagDhami1** [comment]
Notice that the NHS Assurance icons are only visible once the 'Alt Target' Line is set and the icon represents the data points against the 'Alt Target' and not the Main 'Centre Line'. All outlier patterns are enabled.

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/166033455/5f8a3bb1-5c7d-4fb7-abed-7ec09c688a6f)

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/166033455/7451c329-6e43-4894-b665-a2cf5f893d5d)

Strange, when you then toggle the 'Alt Target' on/off the NHS Assurance icon is still visible and still representative of the 'Alt Target' Line.

**Comment by andrjohns** [comment]
Ah that's definitely a bug, thanks for catching!

**Comment by andrjohns** [comment]
Thanks again for the bug report, this is now fixed in the development version

**Comment by JagDhami1** [comment]
Hi Andrew, may be I'm missing something here..... but, should the NHS Assurance icon be based on the Target Line and not the Alt. Target Line. I may have got my wires crossed in my last post, the bug has been fixed, but could you clarify if the original Assurance icon was based off the Target/Centre Line or the Alt. Target Line?
