### ISSUE TITLE
Internal Error: "Cannot read properties of undefined (reading day)

### ISSUE THREAD

**Issue by NOEANDREW** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#250]
Hello! 
I have been using  the SPC Tool for some month with no issues. It has been very usefull.
But yesterday I started having this error

<img width="210" alt="Error SPC Chart" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/120001193/30ae7e98-5ed4-4478-afdd-b42d9e2c1a18">

This is my basic setup for the chart
<img width="92" alt="Error SPC Chart2" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/120001193/1627ce9d-58de-4b54-bc91-2bede5cb573e">

I already reviewed my data source and I couldn't find any errors from my site.
I also tested moving my data source from shared folder  to local pc in order to see if there is related to sharepoint issues.

I noticed that if I remove from ID Key (Date) the "Date-Year" the charts works(see Picture Below), but that affetcs how I want to see the data (I need that to be shown sequentially starting from 2023)

<img width="230" alt="Error SPC Chart2-2" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/120001193/86f71195-bdda-4a75-bd68-e0b93117452a">

<img width="89" alt="Error SPC Chart2-3" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/120001193/6dda4339-453a-44c3-bce6-afc7458f9fc8">

Here you have a PDF screenshot from a report that I saved last week that shows how I used to see the chart
<img width="215" alt="Error SPC Chart0" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/120001193/545142aa-9bb8-46e7-86d8-55a74dd8a7ec">

Do you know what could be generatig this failure condition considering that I havent modified my setup and even last week it was woking correctly?
here you have my calendar and week setup
<img width="437" alt="Error SPC Chart3" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/120001193/503e0cdd-acea-4465-92af-80a7d2300c4b">

<img width="166" alt="Error SPC Chart4" src="https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/120001193/55b1e599-ccd2-418b-95c1-98a96bd5f0ac">

Note: Just in case I set a filter to limit that chart to the las 36 weeks

Regards
Andres Aguilar

**Comment by andrjohns** [comment]
Thanks for the comprehensive bug report and apologies for breaking things! I was making an erroneous assumption that multiple 'ID Key' inputs would only be present in the case of 'Date Hierarchy' types. I've added a fix in #255.

We'll be submitting a new version to MS within the next week.
