### ISSUE TITLE
Incorrect target line with percentage data + incorrect assurance icon with incomplete/variable targets

### ISSUE THREAD

**Issue by MatthewCallus** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#257]
When percentage data is used, I have found issues with the target line. I have tested this with the latest version (1.4.1.2) with screenshot and pbix file below:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/79798278/117e5f2a-a0db-4984-8888-f025317a157d)

[Example.zip](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/files/14634491/Example.zip)

As you can see, when the values are converted to a percentage by either using the **Report as percentage** or **Multiplier** options, the target does not also change.

Additionally, for the SPC with the correct lines (top-right), the assurance icon is incorrect. It appears to be using the initial target (0.75) instead of the latest target (0.50). It should display the grey hit or miss icon, as shown below when 0.50 is used throughout:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/79798278/d2d0742f-bc8d-466d-aceb-cb0df6140eb6)

Additionally, if the target is not complete for the whole period, no assurance icon is shown:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/79798278/6567a83a-e1b2-457e-b3ec-336533fdac29)

What should happen to calculate the Making Data Count assurance icon is the target should be compared to the process limits for the last data point in the chart. That is to say, if there is no target at all or it ends before this, there is no assurance icon; and if there is a target at the end, even if it starts only at the last point, there is an assurance icon.

The assurance icon is used to predict future performance based on the current limits (with caution taken when there is active special cause variation). This can be tricky when dealing with changing targets. For example, if the next data point, April 2024, was to have a new target, we would want assurance against this, not the current target of 50%. It would therefore be great if the target line could be extended on the chart without having to add more data (with the dates continuing and the mean and process limits extended). Then the assurance icon could use the target of the next point if provided.

**Comment by andrjohns** [comment]
Thanks for the clear report and example data!

By default the visual won't scale user-specified targets with the multiplier, but I've added an option to request this:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/13a6596a-cefd-4ce8-939d-901ee181bf3d)

I've also now updated the development version of the visual to correctly handle different user-specified targets over time as well as missing target values, based on the points above.

Thanks!
