### ISSUE TITLE
Limit line points seemingly being calculated for each ID Key (Date) on P Chart

### ISSUE THREAD

**Issue by kaneswanton** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#258]
Hello!

Love the custom viz, just noticed something odd when I present my data via the P Chart, it appears that the limit lines are being calculated for each period, not for the total data being presented.

I'm relatively new to SPC charts but couldn't see anything in other articles saying that was best practice.

![Wobbly Limit Lines](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/163961202/5d16e655-bb9f-4234-b372-060562713eab)

Cheers,
Kane

**Comment by andrjohns** [comment]
Thanks! That is normal behaviour for a P Chart, as the width of the control limits are determined by the size of the denominator in a given period. (Remember that SPC control limits indicate a level of "certainty" in measurement, with smaller denominators you are more uncertain and your control limits will be wider).

If you want a P chart where the limits do not vary over time, then all observations need to have the same denominator
