### ISSUE TITLE
How can we Input Pre-Defined Control Limits & Target Values?

### ISSUE THREAD

**Issue by shs332000** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#261]
I am trying to build an SPC chart based on testing equipment, which have specification limits and target values for each product that I test. How can I have these be my lines on my chart? My end goal is to have a notification system that allows for my maintenance team to be notified when a piece of test equipment is out of control. I know that control limits and specification limits are different, but do we have this capability? Thank you

**Comment by andrjohns** [comment]
Great question! I hadn't considered specification limits before. 

I've added options for these in #262 under the "Line Settings" menu:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/59b7e0ab-92eb-4cee-80b0-f157d1940585)

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/b1925157-3dda-49c6-9f29-ccbb81700c05)

You can try these out using the [development release](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/releases/tag/latest)

 Thanks for the suggestion, let me know if I've missed anything!

**Comment by shs332000** [comment]
Can we also do this for the target value? Can we put our own target value in?

**Comment by andrjohns** [comment]
> Can we also do this for the target value? Can we put our own target value in?

Yes, that's the "Alt. Target" settings in the same dropdown

**Comment by shs332000** [comment]
What are your thoughts on if there is an out of control point, that triggers an email/teams message?

**Comment by andrjohns** [comment]
Unfortunately that's not possible. PowerBI custom visuals are sandboxed and unable to interact with the external environment. APIs for communicating outside of the sandbox are only for very specific purposes (like propagating data selections for highlighting/filtering)

**Comment by shs332000** [comment]
Okay thank you. Does this graph acount for all out of control rules?

**Comment by andrjohns** [comment]
The available rules and their respective options can be seen under the 'Outlier Highlighting' menu, currently:

- Astronomical points
- Shifts
- Trends
- Two-in-three outside warning limit

**Comment by shs332000** [comment]
I am wondering what "Imp", "Det", "Neutral (Low)", and "Neutral (High)" means for outlier highlighting in my case. I am doing it on test results, where there is Upper and Lower specification limits, that aren't always equi-distant from the target value. (ex: the LSL could be 0, target value could be 30, and USL could be 100). What should I do for color highlighting in this example? I want to highlight the "out of control" points red so on the dashboard my maintenance team can see what test failed. Thank you!
