### ISSUE TITLE
Implementing minimum date on X-axis

### ISSUE THREAD

**Issue by csumm828** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#285]
I was curious if you were planning on adding any options to allow users to incorporate a minimum date value in the x-axis. Similar to some of the existing charts / visuals out there for Power BI, it would be a benefit to have the option to establish a minimum for the range. I realize we can hard code this and/or use the filters in Power BI, but some custom DAX expressions (such as rolling 12 month periods), tend to work best when you can enforce a range in the visual itself.

**Comment by andrjohns** [comment]
Not at the moment, but we can definitely add it to the roadmap.

Just a quick clarification, would the intended result be the ability to only show the most recent N months? For example, if 24 months of data is provided, the visual only uses the most recent 12?

**Comment by csumm828** [comment]
My apologies, I did not see this response, I could see that scenario and I think that would be helpful, thank you!

**Comment by andrjohns** [comment]
The 'Data Settings' menu now has options for selecting the number of points to use for calculating limits and centerlines:
