### ISSUE TITLE
Feature Request - NHS Icons only for a summary page.

### ISSUE THREAD

**Issue by SeanOS66** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#294]
Hi, I recently started using your SPC visual (and I work in the NHS in Suffolk, UK so your work is greatly appreciated). 

The only thing that I think is missing would be the ability to easily turn off all the graphs, just leaving the NHS Icons. By tweaking just about every setting and making the size of the Icons really large you can almost mimic a "Summary" of each KPI on a page, but as you hover over the now invisible (white on white) graph, it still tries to highlights points, which is distracting and messy.

What would be wonderful would be an option to "Only Show Icons" and this would only show the Icons (Variations & Assurance) which would fill the visual, and these could then be shrunk down to a size where many could be placed on a cover page and would highlight what management should be focussing on. All we would need to do is to provide the KPI, Target and what is good. Then repeat this several times for all the KPI's to go on this summary page.
If this Summary Visual could became an action button we could then enter a Bookmark to jump to the detail page where we could show the full SPC chart for this exceptional KPI.

**Comment by carolineb936** [comment]
Yes Please this would be really useful

**Comment by Yayabee** [comment]
Logged in today to raise the issue and found out it's already here.

**Comment by hannaho1** [comment]
This would be so useful! I have tried the idea of changing everything to white and it does work but agree it is quite messy. The ability to turn off the graph and show only icons would be very helpful :)

**Comment by andrjohns** [comment]
A summary table with icons is now implemented ([see guide here](https://aus-doh-safety-and-quality.github.io/PowerBI-SPC/SummaryTable.html) for more details)
