### ISSUE TITLE
Add function to extend baseline from specific, or relative data point

### ISSUE THREAD

**Issue by bsre01** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#298]
Currently the 'Target' mean line is calculated from all points within the visual, however for testing for improvement against previous performance it would be more useful if we could select which data points were baseline data and only use those for calculating the mean. This could be through a relative data points option (i.e - use first x points as baseline), or a specific selection (end baseline at date x).

As an added bonus, if it was possible to set the format of the target line before and after this point independently that would be the cherry on top - i.e having it a solid line throughout the baseline period and dashed after it is extended.

**Comment by bsre01** [comment]
This could also be sort of achieved by letting us choose which target line is used for outlier highlighting rules. Since we can set a custom value for the Alt. Target, if we could also use the Alt. Target as the calculating mean for shifts, limits etc, we could effectively use a value we have calculated from previous performance for this line, hide the original line and have an 'extended' mean this way.

The more direct way above would be better, but if this is an easier option it would do the job fairly well.

**Comment by carolineb936** [comment]
Agree we would like this

**Comment by andrjohns** [comment]
The `Data Settings` menu now includes options for selecting the number of points to use in limit/centerline calculations, and whether to subset from the start or the end of data points:

![image](https://github.com/user-attachments/assets/7acc4ab2-313a-4b4e-80d1-a1149e78be3e)
