### ISSUE TITLE
Error with run charts with target if assurance icon is turned on

### ISSUE THREAD

**Issue by MatthewCallus** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#303]
When the following settings are applied:

- **Chart Type** is set to **run- Run Chart**
- **Show Assurance Icons** is turned **On**
- **Additional Target Value** is not empty

The visual returns the following:

```
Internal Error! Please file a bug report with the following text:

Cannot read properties of undefined (reading 'length')
```
This is not a problem when **Show Variation Icons** is turned **On**.  In that case, the icon appears (always grey?) although it would make sense for it not to be there.

I can get around this issue by manually turning the icon(s) off but I have set up my SPC charts using functions so that the visual doesn't need to be changed, with it changing the chart type, target, axis, etc. based on the data fed in. As there are no function options to turn the icons on/off, I cannot do it for that.

So can it be changed so that the icons are simply ignored (even if left on) for run charts or to also be configurable? And obviously for the error to go away. 😊

Thanks
Matt

**Comment by pli9** [comment]
Hi Matthew, thanks for your bug report! Fortunately, this issue has already been resolved in the development version, it'll be wrapped in the next submission to Microsoft.

Here is a link to the particular commit that resolves this issue:
https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/commit/037a697df38c5ef7a4804e53e07052b49836a700
