### ISSUE TITLE
Can't update Date format in Chart

### ISSUE THREAD

**Issue by csumm828** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#306]
We are using this visual in multiple reports, but one issue that keeps popping up is when a user needs MM/DD/YYYY, changing the locale to en-US doesn't change it. It still shows DD/MM/YYYY. We tried different formats for the data type, but that didn't appear to have an impact. Is there some other requirement to be able to use the US format in the visual?

**Comment by shauneccles** [comment]
Have you tried to change the date format of the column in the data model? You should be able to select it and change the format to the desired locale.

![image](https://github.com/user-attachments/assets/c3f049ee-f6e4-4a77-8404-c0c09df57840)

**Comment by csumm828** [comment]
Good morning,

Thank you for the update and the suggestion. We did try to update the formats in the desktop client for the column / field in the data model as well and that doesn't appear to have an impact. I have attached some screenshots to show you what we are seeing on our end. 

![Date Filter](https://github.com/user-attachments/assets/c9b063e2-9df7-4fd8-ba98-7c963c160b76)
![Date Format](https://github.com/user-attachments/assets/6566c322-2132-40dc-bd4e-edea83089779)
![Date Format in SPC Chart](https://github.com/user-attachments/assets/2a0f2acc-c2a3-4806-9333-44107cb76ff1)
![Date Format Selections in SPC Chart](https://github.com/user-attachments/assets/cdd281b9-3603-4824-93f0-a276d7f43d0f)


Here's a breakdown of the screenshots, we have a date format in the Power BI desktop client that aligns with your recommendations, that's set. We also have a filter leveraging that date format and that appears as expected. We have also chosen the right date format in the SPC Visual menu. Where it breaks is if you look at the date format at the bottom of the SPC Chart, instead of MM/DD/YYYY like it is everywhere else, its showing DD/MM/YYYY. All of our reports use either MM/DD/YYYY or MM-DD-YYYY or MM-YYYY. So we would need to see if it would be possible to update this somehow. I'm hoping it something simple, but I would love to get your thoughts.

Thanks in advance for any guidance or insight you can provide.

**Comment by andrjohns** [comment]
@csumm828 sorry for the delay! This should now be fixed
