### ISSUE TITLE
Broken URL in documentation: NHS Making data count guide

### ISSUE THREAD

**Issue by alexbdaniel** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#325]
The [documentation](https://aus-doh-safety-and-quality.github.io/PowerBI-SPC/) references an NHS guide. 

The href = `[url](https://www.england.nhs.uk/publication/making-data-count/)`. This takes me to "https://aus-doh-safety-and-quality.github.io/PowerBI-SPC/[url](https://www.england.nhs.uk/publication/making-data-count/)".

If the documentation is written in markdown, the syntax should be 
`[NHS Making Data Count Guide](https://www.england.nhs.uk/publication/making-data-count/)`

Using Edge Version 124.0.2478.121 (Official build) (64-bit)

Obviously low priority, just letting you guys know. Thank you for the SPC visual, very nice.

**Comment by shaunes-rmh** [comment]
There's an open PR here that will fix this - https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC-Docs/pull/1

**Comment by alexbdaniel** [comment]
oh cool thanks, didn't see that

**Comment by andrjohns** [comment]
Thanks for the reminder, PR merged and website updating now
