### ISSUE TITLE
Mini charts

### ISSUE THREAD

**Issue by Samuhnm** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#341]
It would be great if the charts could be scaled down really small so users could just see the shape of the line and the background colour code, and click on it to view bigger if interested.  Screenshot shows what currently happens when getting really small.

![image](https://github.com/user-attachments/assets/ba0d6158-fa61-42bb-b65b-34fd9ef6e47e)

**Comment by andrjohns** [comment]
I believe this should already be possible with the current formatting settings - you can choose smaller fonts (or no text), smaller sizes of points, thicker/thinner lines, etc

**Comment by andrjohns** [comment]
I'm going to close this since I think the question has been addressed, but feel free to let me know if not!
