### ISSUE TITLE
Summary table Grouping field not available

### ISSUE THREAD

**Issue by Sashimisan77** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#343]
When I attempt to create a summary table. My fields available do not match the fields in the web documentation.
In the documentation is says to use the field _Grouping (Summary Table)_.
![image](https://github.com/user-attachments/assets/0bf281d0-c91f-4e05-a2f7-8b5890f4019f)
Instead, I only see Rebaseline Groupings
![image](https://github.com/user-attachments/assets/4a0239f7-e045-41a4-9af2-946c9e73a578)

Can you please advise?

**Comment by andrjohns** [comment]
The Summary Table grouping feature is still in development and is only available in the development version of the visual. For instructions on installation, [see this page of the documentation](https://aus-doh-safety-and-quality.github.io/PowerBI-SPC/Installation.html#development-release)

**Comment by Sashimisan77** [comment]
Thanks very much for the quick response.
