### ISSUE TITLE
Additional Target Value field not available

### ISSUE THREAD

**Issue by Sashimisan77** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#344]
In both the stable release and the development release, the _Additional Target Value_ field does not appear to be available.
![image](https://github.com/user-attachments/assets/ebbccbce-2914-4a99-9c18-a8cf37707a83)

I am looking in the _Data Settings_ section which appears to end with the _Truncate Upper/Lower Limits_ fields
![image](https://github.com/user-attachments/assets/0d24e2e5-09fc-418c-be49-a2b733970ccd)

**Comment by andrjohns** [comment]
It's under the 'Line Settings' menu, in the 'Alt. Target' dropdown

**Comment by Sashimisan77** [comment]
How embarrassing. You even **bolded** the text explaining that. I apologize.
![image](https://github.com/user-attachments/assets/d1c739c1-3f8c-4ed5-8513-d3600e95d201)
