### ISSUE TITLE
Which SPC chart to use for Median

### ISSUE THREAD

**Issue by Sashimisan77** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#352]
We have several metrics at our org that calculate the median minutes between events. Which SPC chart option is appropriate for trending a median over time?

**Comment by andrjohns** [comment]
The development version of the visual shows options for an i-chart with a median Centerline (either with limits from the average moving range or median moving range)

**Comment by Sashimisan77** [comment]
Thank you
