### ISSUE TITLE
Adding additional lines on to SPC

### ISSUE THREAD

**Issue by bgordonnhs** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#85]
Hello,

This tool is almost absolutely perfect for our use! Thank you!!!

Wondering if it's possible to add in extra lines - e.g. we'd like to add the performance target/goal in as a red line, so this would just be a straight line at a certain number. Is this possible?

Thanks!
Bethany

**Comment by andrjohns** [comment]
Great to hear that it's useful, and thanks for the feedback! You can now add another line to the plot using the "Additional Target Value" option in the "Data Settings" menu (with width/colour/type aesthetics under the "Line Settings" menu)

**Comment by bgordonnhs** [comment]
Amazing - thank you!!
