### ISSUE TITLE
Changing format of axis values

### ISSUE THREAD

**Issue by bgordonnhs** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#86]
Hello,

Is it possible to change the format of the axis values e.g. changing y axis from a decimal to a %?

Thanks!
Bethany

**Comment by bgordonnhs** [comment]
Also changing the colour of the axis text

**Comment by andrjohns** [comment]
> Is it possible to change the format of the axis values e.g. changing y axis from a decimal to a %?

The visual will automatically use % units when a p or p-prime chart is used with a multiplier of 1, which I've updated to also use the % label for a multiplier of 100. Does that cover your use-case or were you thinking of other chart types?

> Also changing the colour of the axis text

Options for selecting font colour of labels and ticks now added

**Comment by bgordonnhs** [comment]
Ah yes, that's my fault - that's worked now, thank you!

**Comment by bgordonnhs** [comment]
Just another thing on this one (sorry!) - can't see an option to change date formats from DD/MM/YYYY to another option (we often go for MMM-YY).  I tried amending the format of the date field in the tables tab but it made no difference to the viz. I've achieved this by using a text field in the MMM-YY format and sorted it by the date field but it would be useful to be able to just use the date field and amend the format in the viz if that's possible?
On a similar note, being able to change the number of decimal places for the values on the y-axis would be great!

**Comment by bgordonnhs** [comment]
Also (and this is me being REALLY picky sorry) being able to change the colour of the axis lines would be the icing on the cake!

**Comment by andrjohns** [comment]
Oh good idea. I've now added an option to the "Data Settings" menu to select the number of decimals to report (will change both the y-axis and the tooltip), and options for the axis colours and date formats to the respective axis settings menus

**Comment by bgordonnhs** [comment]
Thanks so much! This is great!!

As a super cheeky ask, wondering if "MMM-YY" (e.g Jan-23) could be added to the date formats?

**Comment by andrjohns** [comment]
Great idea! I've significantly expanded the number of date formatting options - let me know if I've missed any!

**Comment by bgordonnhs** [comment]
This is great - thanks!

**Comment by bgordonnhs** [comment]
Sorry, something else I've noticed with the axes!!

Struggling to get the x axis to cross the y axis at 0: 
![image](https://user-images.githubusercontent.com/122809109/215745418-53bae69c-e2e1-4966-9768-9613cf8c1b5e.png)

Even when selecting the lower limit to be 0 this remains the same.

On that note, would it be possible to enter either an upper/lower limit on the axis without needed to enter the other limit.

e.g. ofter we want to cap our SPCs y axis at 0 as it doesn't make sense for a negative number for that given metric, even though the calculated lower limit is below 0, but the upper limit does not matter.  e.g. see below: 
![image](https://user-images.githubusercontent.com/122809109/215745984-d16da50d-9b39-44e2-a2af-b54946f918e6.png)

Another example is where a metric would never be above 100% but the upper limit is above 100% so we cap the SPC at 100% but don't want to enter a lower limit.

**Comment by andrjohns** [comment]
Point 1 is now fixed (setting the lower limit to 0 is now handled correctly), point 2 should already be possible (but let me know if you're encountering a particular error)

**Comment by andrjohns** [comment]
For point 3 - I've expanded the tick formatting options in #115 with an additional option for the tick rotation and the number of ticks. 

Unfortunately, more granular control of which individual ticks to render is not possible (or at least not simple to implement and expose)
