### ISSUE TITLE
Adding multiple dates to split limits

### ISSUE THREAD

**Issue by bgordonnhs** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#94]
Hello, 

It looks like you can add multiple dates into this field:
![image](https://user-images.githubusercontent.com/122809109/213439563-ac3ebf7c-a4e4-4e1c-93ab-abacecd4c442.png)

But how should the dates be separated, I've tried a space,  ',' and ';' but none seem to work?
![image](https://user-images.githubusercontent.com/122809109/213439975-4d64ad9b-2094-452c-b2b0-18393b0b311f.png)
![image](https://user-images.githubusercontent.com/122809109/213439846-79591ecc-bfb8-4ed3-84a6-7b170c6c94d9.png)
![image](https://user-images.githubusercontent.com/122809109/213439876-eb72655e-5c76-466c-975a-0f22ae62dd37.png)

Thanks!
Bethany

**Comment by andrjohns** [comment]
Ah yes, entering the dates to split at isn't compatible with the new date formatting. I'm in the process of replacing this input with an interactive menu (i.e., clicking on a given point opens a menu with the option to split the limits at that point), so that should be workable soon

**Comment by andrjohns** [comment]
I've taken an even simpler approach to this. I've replaced the current option with a checkbox called "Split Limits on Click". When that's enabled, clicking on a plot point will split the limits at that point (instead of the default highlight/filter behaviour). It's much easier to split at multiple points this way, and you can un-split by clicking the point again

**Comment by thomasbreese** [comment]
The split limits don't seem to be working for me either. We might also have dates saved in a table that we know we want to recalculate on, is it possible to get this with conditional formatting?

**Comment by andrjohns** [comment]
@thomasbreese @bgordonnhs Apologies for the delays in getting to this. I've now added a new data field "Rebaseline Groupings" where you can specify the groups for the limits:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/88e2e3d2-f42f-42ed-ab63-cab5f9c6faa9)

Where the "Groupings" argument would be setup like so:

![image](https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/assets/27717896/9e99c852-1be2-4739-a40c-0161c1776713)
