### ISSUE TITLE
Limits calculations

### ISSUE THREAD

**Issue by bgordonnhs** [AUS-DOH-Safety-and-Quality/PowerBI-SPC#95]
Hello,

Would you be willing to share your calculation for the limits please as it differs to what we are used to? It would be good to understand the difference!

Thanks,
Bethany

**Comment by andrjohns** [comment]
The calculations for each chart type can be found in this folder: https://github.com/AUS-DOH-Safety-and-Quality/PowerBI-SPC/tree/main/src/Limit%20Calculations

And a summary of the general formulas used are in this vignette: https://anhoej.github.io/qicharts2/articles/qicharts2.html#appendix-1-calculating-3-sigma-limits

**Comment by bgordonnhs** [comment]
Thanks for this - I think our in-house tool wasn't as precise as this so that's a good reason for it being different!
